language: node_js
node_js:
  - "11"
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

before_script:
  - npm install -g @angular/cli

install:
  - npm install -g yarn
  - npm install

script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/pizza-pwa
  on:
    branch: master